import { Component } from '@angular/core';
import * as i0 from "@angular/core";
export class HeroVisual {
    static ɵfac = function HeroVisual_Factory(__ngFactoryType__) { return new (__ngFactoryType__ || HeroVisual)(); };
    static ɵcmp = /*@__PURE__*/ i0.ɵɵdefineComponent({ type: HeroVisual, selectors: [["app-hero-visual"]], decls: 15, vars: 0, consts: [["aria-hidden", "true", 1, "hero-art"], [1, "hero-art__star"], [1, "hero-art__question"], [1, "hero-art__phone"], [1, "hero-art__speaker"], [1, "hero-art__screen"], [1, "hero-art__bar", "hero-art__bar--one"], [1, "hero-art__bar", "hero-art__bar--two"], [1, "hero-art__bar", "hero-art__bar--three"], [1, "hero-art__check"], [1, "hero-art__bubble"]], template: function HeroVisual_Template(rf, ctx) { if (rf & 1) {
            i0.ɵɵdomElementStart(0, "div", 0)(1, "span", 1);
            i0.ɵɵtext(2, "\u2605");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(3, "span", 2);
            i0.ɵɵtext(4, "?");
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(5, "div", 3);
            i0.ɵɵdomElement(6, "div", 4);
            i0.ɵɵdomElementStart(7, "div", 5);
            i0.ɵɵdomElement(8, "span", 6)(9, "span", 7)(10, "span", 8);
            i0.ɵɵdomElementStart(11, "span", 9);
            i0.ɵɵtext(12, "\u2713");
            i0.ɵɵdomElementEnd()()();
            i0.ɵɵdomElementStart(13, "span", 10);
            i0.ɵɵtext(14, "\u2022\u2022\u2022");
            i0.ɵɵdomElementEnd()();
        } }, styles: ["[_nghost-%COMP%] {\n  display: block;\n}\n\n.hero-art[_ngcontent-%COMP%] {\n  position: relative;\n  width: 26.625rem;\n  height: 26.25rem;\n}\n\n.hero-art__phone[_ngcontent-%COMP%] {\n  position: absolute;\n  inset: 2rem 4.3rem 1rem;\n  padding: 1.2rem;\n  border: 0.75rem solid var(--%NS%color-cream);\n  border-radius: 3rem;\n  background: var(--%NS%color-purple);\n  box-shadow: 1rem 1rem 0 rgb(255 207 161 / 45%);\n  transform: rotate(8deg);\n}\n\n.hero-art__speaker[_ngcontent-%COMP%] {\n  width: 3rem;\n  height: 0.4rem;\n  margin: 0 auto 1.25rem;\n  border-radius: 1rem;\n  background: var(--%NS%color-orange);\n}\n\n.hero-art__screen[_ngcontent-%COMP%] {\n  display: grid;\n  gap: 1.1rem;\n  padding: 2.3rem 1.4rem;\n  border-radius: 1.5rem;\n  background: var(--%NS%color-surface);\n}\n\n.hero-art__bar[_ngcontent-%COMP%] {\n  height: 1.25rem;\n  border-radius: 2rem;\n  background: var(--%NS%color-orange-soft);\n}\n\n.hero-art__bar--two[_ngcontent-%COMP%] {\n  width: 72%;\n}\n.hero-art__bar--three[_ngcontent-%COMP%] {\n  width: 88%;\n}\n\n.hero-art__check[_ngcontent-%COMP%] {\n  display: grid;\n  width: 4rem;\n  height: 4rem;\n  place-items: center;\n  margin: 1rem auto 0;\n  border-radius: 50%;\n  background: var(--%NS%color-orange);\n  color: var(--%NS%color-purple);\n  font: 2.5rem/1 var(--%NS%font-body);\n}\n\n.hero-art__star[_ngcontent-%COMP%], \n.hero-art__question[_ngcontent-%COMP%], \n.hero-art__bubble[_ngcontent-%COMP%] {\n  position: absolute;\n  z-index: 2;\n  color: var(--%NS%color-orange);\n  font-family: var(--%NS%font-heading);\n}\n\n.hero-art__star[_ngcontent-%COMP%] {\n  top: 0;\n  right: 1.2rem;\n  font-size: 4.5rem;\n}\n.hero-art__question[_ngcontent-%COMP%] {\n  bottom: 0;\n  left: 0;\n  font-size: 7rem;\n}\n.hero-art__bubble[_ngcontent-%COMP%] {\n  top: 4.2rem;\n  left: 0;\n  padding: 0 1rem 0.6rem;\n  border: 0.35rem solid var(--%NS%color-orange);\n  border-radius: 1.5rem;\n  font-size: 2.5rem;\n}\n\n@media (max-width: 48rem) {\n  .hero-art[_ngcontent-%COMP%] {\n    width: 18rem;\n    height: 18rem;\n  }\n  .hero-art__phone[_ngcontent-%COMP%] {\n    inset: 1.5rem 3.5rem 0.5rem;\n    border-width: 0.5rem;\n  }\n  .hero-art__screen[_ngcontent-%COMP%] {\n    gap: 0.7rem;\n    padding: 1.2rem 0.8rem;\n  }\n  .hero-art__star[_ngcontent-%COMP%] {\n    font-size: 3rem;\n  }\n  .hero-art__question[_ngcontent-%COMP%] {\n    font-size: 4.5rem;\n  }\n  .hero-art__bubble[_ngcontent-%COMP%] {\n    top: 3rem;\n    font-size: 1.5rem;\n  }\n}"] });
}
(() => { (typeof ngDevMode === "undefined" || ngDevMode) && i0.ɵsetClassMetadata(HeroVisual, [{
        type: Component,
        args: [{ selector: 'app-hero-visual', template: "<div class=\"hero-art\" aria-hidden=\"true\">\n  <span class=\"hero-art__star\">\u2605</span>\n  <span class=\"hero-art__question\">?</span>\n  <div class=\"hero-art__phone\">\n    <div class=\"hero-art__speaker\"></div>\n    <div class=\"hero-art__screen\">\n      <span class=\"hero-art__bar hero-art__bar--one\"></span>\n      <span class=\"hero-art__bar hero-art__bar--two\"></span>\n      <span class=\"hero-art__bar hero-art__bar--three\"></span>\n      <span class=\"hero-art__check\">\u2713</span>\n    </div>\n  </div>\n  <span class=\"hero-art__bubble\">\u2022\u2022\u2022</span>\n</div>\n", styles: [":host {\n  display: block;\n}\n\n.hero-art {\n  position: relative;\n  width: 26.625rem;\n  height: 26.25rem;\n}\n\n.hero-art__phone {\n  position: absolute;\n  inset: 2rem 4.3rem 1rem;\n  padding: 1.2rem;\n  border: 0.75rem solid var(--color-cream);\n  border-radius: 3rem;\n  background: var(--color-purple);\n  box-shadow: 1rem 1rem 0 rgb(255 207 161 / 45%);\n  transform: rotate(8deg);\n}\n\n.hero-art__speaker {\n  width: 3rem;\n  height: 0.4rem;\n  margin: 0 auto 1.25rem;\n  border-radius: 1rem;\n  background: var(--color-orange);\n}\n\n.hero-art__screen {\n  display: grid;\n  gap: 1.1rem;\n  padding: 2.3rem 1.4rem;\n  border-radius: 1.5rem;\n  background: var(--color-surface);\n}\n\n.hero-art__bar {\n  height: 1.25rem;\n  border-radius: 2rem;\n  background: var(--color-orange-soft);\n}\n\n.hero-art__bar--two {\n  width: 72%;\n}\n.hero-art__bar--three {\n  width: 88%;\n}\n\n.hero-art__check {\n  display: grid;\n  width: 4rem;\n  height: 4rem;\n  place-items: center;\n  margin: 1rem auto 0;\n  border-radius: 50%;\n  background: var(--color-orange);\n  color: var(--color-purple);\n  font: 2.5rem/1 var(--font-body);\n}\n\n.hero-art__star,\n.hero-art__question,\n.hero-art__bubble {\n  position: absolute;\n  z-index: 2;\n  color: var(--color-orange);\n  font-family: var(--font-heading);\n}\n\n.hero-art__star {\n  top: 0;\n  right: 1.2rem;\n  font-size: 4.5rem;\n}\n.hero-art__question {\n  bottom: 0;\n  left: 0;\n  font-size: 7rem;\n}\n.hero-art__bubble {\n  top: 4.2rem;\n  left: 0;\n  padding: 0 1rem 0.6rem;\n  border: 0.35rem solid var(--color-orange);\n  border-radius: 1.5rem;\n  font-size: 2.5rem;\n}\n\n@media (max-width: 48rem) {\n  .hero-art {\n    width: 18rem;\n    height: 18rem;\n  }\n  .hero-art__phone {\n    inset: 1.5rem 3.5rem 0.5rem;\n    border-width: 0.5rem;\n  }\n  .hero-art__screen {\n    gap: 0.7rem;\n    padding: 1.2rem 0.8rem;\n  }\n  .hero-art__star {\n    font-size: 3rem;\n  }\n  .hero-art__question {\n    font-size: 4.5rem;\n  }\n  .hero-art__bubble {\n    top: 3rem;\n    font-size: 1.5rem;\n  }\n}\n"] }]
    }], null, null); })();
(() => { (typeof ngDevMode === "undefined" || ngDevMode) && i0.ɵsetClassDebugInfo(HeroVisual, { className: "HeroVisual", filePath: "src/app/shared/components/hero-visual/hero-visual.ts", lineNumber: 8 }); })();
